from industries import (
    alumina_refinery,
    aluminium_plant,
    ammonia_plant,
    appliance_factory,
    arable_farm,
    assembly_plant,
    bakery,
    basic_oxygen_furnace,
    bauxite_mine,
    biorefinery,
    blast_furnace,
    body_plant,
    brewery,
    brick_works,
    builders_yard,
    bulk_terminal,
    carbon_black_plant,
    cement_plant,
    chemical_plant,
    chlor_alkali_plant,
    chromite_mine,
    cider_mill,
    civil_explosives_facility,
    clay_pit,
    cleaning_products_factory,
    coal_mine,
    coffee_estate,
    coke_oven,
    component_factory,
    copper_concentrator,
    copper_mine,
    copper_refinery,
    cryo_plant,
    dairy,
    dairy_farm,
    diamond_mine,
    dredging_site,
    edible_oil_refinery,
    electric_arc_furnace,
    electrical_works,
    engine_plant,
    ethylene_cracker,
    farm,
    farm_supply_yard,
    ferrochrome_smelter,
    fertiliser_plant,
    fischer_tropsch_plant,
    fish_farm,
    fishing_grounds,
    fishing_harbour,
    flour_mill,
    food_market,
    food_processor,
    forest,
    fruit_packing_plant,
    fruit_plantation,
    furniture_factory,
    general_store,
    glass_works,
    hardware_store,
    herding_coop,
    hotel,
    integrated_steel_mill,
    iron_ore_mine,
    iron_works,
    junk_yard,
    latex_processor,
    lime_kiln,
    limestone_mine,
    liquids_terminal,
    lumber_yard,
    machine_shop,
    manganese_mine,
    meat_packing_plant,
    metal_workshop,
    nitrate_mine,
    oil_refinery,
    oil_rig,
    oil_wells,
    orchard_piggery,
    paint_factory,
    paper_mill,
    peatlands,
    petrol_pump,
    phosphate_mine,
    phosphoric_acid_plant,
    plastics_plant,  # should be one of the polymer plants (pvc?)
    # from industries import plaza,
    polyethylene_plant,
    polypropylene_plant,
    port,
    potash_mine,
    power_plant,
    pyrite_mine,
    pyrite_smelter,
    quarry,
    ranch,
    recycling_depot,
    recycling_plant,
    rubber_plantation,
    salt_evaporator,
    salt_mine,
    sawmill,
    seaweed_farm,
    sheep_farm,
    sheet_and_pipe_mill,
    slag_grinding_plant,
    smithy_forge,
    soda_ash_mine,
    solvay_plant,
    # from industries import steel_mill,
    stockyard,
    sugar_refinery,
    sulphuric_acid_plant,
    supply_yard,
    tar_sands_mine,
    textile_mill,
    tinplate_works,
    trading_post,
    tyre_plant,
    vehicle_distributor,
    vineyard,
    wharf,
    wire_and_section_mill,
)

registered_industries = []

alumina_refinery.industry.register()
aluminium_plant.industry.register()
ammonia_plant.industry.register()
appliance_factory.industry.register()
arable_farm.industry.register()
assembly_plant.industry.register()
bakery.industry.register()
basic_oxygen_furnace.industry.register()
bauxite_mine.industry.register()
biorefinery.industry.register()
blast_furnace.industry.register()
body_plant.industry.register()
brewery.industry.register()
brick_works.industry.register()
builders_yard.industry.register()
bulk_terminal.industry.register()
carbon_black_plant.industry.register()
cement_plant.industry.register()
chemical_plant.industry.register()
chlor_alkali_plant.industry.register()
chromite_mine.industry.register()
cider_mill.industry.register()
civil_explosives_facility.industry.register()
clay_pit.industry.register()
cleaning_products_factory.industry.register()
coal_mine.industry.register()
coffee_estate.industry.register()
coke_oven.industry.register()
component_factory.industry.register()
copper_concentrator.industry.register()
copper_mine.industry.register()
copper_refinery.industry.register()
cryo_plant.industry.register()
dairy.industry.register()
dairy_farm.industry.register()
diamond_mine.industry.register()
dredging_site.industry.register()
edible_oil_refinery.industry.register()
electric_arc_furnace.industry.register()
electrical_works.industry.register()
engine_plant.industry.register()
ethylene_cracker.industry.register()
farm.industry.register()
farm_supply_yard.industry.register()
ferrochrome_smelter.industry.register()
fertiliser_plant.industry.register()
fischer_tropsch_plant.industry.register()
fish_farm.industry.register()
fishing_grounds.industry.register()
fishing_harbour.industry.register()
flour_mill.industry.register()
food_market.industry.register()
food_processor.industry.register()
forest.industry.register()
fruit_packing_plant.industry.register()
fruit_plantation.industry.register()
furniture_factory.industry.register()
general_store.industry.register()
glass_works.industry.register()
hardware_store.industry.register()
herding_coop.industry.register()
hotel.industry.register()
integrated_steel_mill.industry.register()
iron_ore_mine.industry.register()
iron_works.industry.register()
junk_yard.industry.register()
latex_processor.industry.register()
lime_kiln.industry.register()
limestone_mine.industry.register()
liquids_terminal.industry.register()
lumber_yard.industry.register()
machine_shop.industry.register()
manganese_mine.industry.register()
meat_packing_plant.industry.register()
metal_workshop.industry.register()
nitrate_mine.industry.register()
oil_refinery.industry.register()
oil_rig.industry.register()
oil_wells.industry.register()
orchard_piggery.industry.register()
paint_factory.industry.register()
paper_mill.industry.register()
peatlands.industry.register()
petrol_pump.industry.register()
phosphate_mine.industry.register()
phosphoric_acid_plant.industry.register()
plastics_plant.industry.register()
# plaza.industry.register()
polyethylene_plant.industry.register()
polypropylene_plant.industry.register()
port.industry.register()
potash_mine.industry.register()
power_plant.industry.register()
pyrite_mine.industry.register()
pyrite_smelter.industry.register()
quarry.industry.register()
ranch.industry.register()
recycling_depot.industry.register()
recycling_plant.industry.register()
rubber_plantation.industry.register()
salt_evaporator.industry.register()
salt_mine.industry.register()
sawmill.industry.register()
seaweed_farm.industry.register()
sheep_farm.industry.register()
sheet_and_pipe_mill.industry.register()
slag_grinding_plant.industry.register()
smithy_forge.industry.register()
soda_ash_mine.industry.register()
solvay_plant.industry.register()
# steel_mill.industry.register()
stockyard.industry.register()
sugar_refinery.industry.register()
sulphuric_acid_plant.industry.register()
supply_yard.industry.register()
tar_sands_mine.industry.register()
textile_mill.industry.register()
tinplate_works.industry.register()
trading_post.industry.register()
tyre_plant.industry.register()
vehicle_distributor.industry.register()
vineyard.industry.register()
wharf.industry.register()
wire_and_section_mill.industry.register()
