# keep these alphabetised for ease of maintaining
from cargos import (
    acetic_acid,
    acid,
    aggregates,
    alcohol,
    alloy_steel,
    aluminia,
    aluminium,
    ammonia,
    ammonium_nitrate,
    bauxite,
    beans,
    biomass,
    building_materials,
    carbon_black,
    carbon_steel,
    cassava,
    cast_iron,
    cement,
    chemicals,
    chlorine,
    chromite_ore,
    clay,
    cleaning_agents,
    coal,
    coal_tar,
    coffee,
    coke,
    concrete_products,
    copper,
    copper_concentrate,
    copper_ore,
    cranes_and_hoists,
    diamonds,
    edible_oil,
    electrical_parts,
    engineering_supplies,
    ethylene,
    explosives,
    farm_supplies,
    ferrochrome,
    fertiliser,
    fish,
    fish_and_meat,
    flour,
    food,
    food_additives,
    forgings_and_castings,
    formic_acid,
    fruits,
    furniture,
    glass,
    goods,
    grain,
    hardware,
    hydrochloric_acid,
    hydrogen,
    iron_ore,
    kaolin,
    lifting_equipment,
    limestone,
    livestock,
    logs,
    lumber,
    lye,
    mail,
    maize,
    manganese,
    meat,
    methanol,
    milk,
    naphtha,
    nickel,
    nitrates,
    nitrogen,
    nuts,
    oil,
    oil_seeds,
    oxygen,
    packaging,
    paints_and_coatings,
    paper,
    passengers,
    peat,
    petrol,
    phosphate,
    phosphoric_acid,
    pig_iron,
    pipe,
    pipework,
    plant_fibres,
    plastic_parts,
    plastics,
    potash,
    propylene,
    pumps_and_valves,
    pyrite_ore,
    quicklime,
    rare_metals,
    raw_latex,
    rebar,
    recyclables,
    rubber,
    salt,
    sand,
    scrap_metal,
    slag,
    soda_ash,
    stainless_steel,
    steel,
    steel_merchant_bar,
    steel_pipe,
    steel_sections,
    steel_sheet,
    steel_tube,
    steel_wire_rod,
    steel_wire_rope,
    stone,
    sugar,
    sugar_beet,
    sugarcane,
    sulphur,
    sulphuric_acid,
    textiles,
    timber,
    tin,
    tinplate,
    tyre_cord,
    tyres,
    urea,
    vehicle_bodies,
    vehicle_engines,
    vehicle_parts,
    vehicles,
    welding_consumables,
    wool,
    yarn,
    zinc,
)

registered_cargos = []

acetic_acid.cargo.register()
acid.cargo.register()
aggregates.cargo.register()
alcohol.cargo.register()
alloy_steel.cargo.register()
aluminia.cargo.register()
aluminium.cargo.register()
ammonia.cargo.register()
ammonium_nitrate.cargo.register()
bauxite.cargo.register()
beans.cargo.register()
biomass.cargo.register()
building_materials.cargo.register()
carbon_black.cargo.register()
carbon_steel.cargo.register()
cassava.cargo.register()
cast_iron.cargo.register()
cement.cargo.register()
chemicals.cargo.register()
chlorine.cargo.register()
chromite_ore.cargo.register()
clay.cargo.register()
cleaning_agents.cargo.register()
coal.cargo.register()
coal_tar.cargo.register()
coffee.cargo.register()
coke.cargo.register()
copper.cargo.register()
copper_concentrate.cargo.register()
copper_ore.cargo.register()
cranes_and_hoists.cargo.register()
diamonds.cargo.register()
edible_oil.cargo.register()
electrical_parts.cargo.register()
engineering_supplies.cargo.register()
ethylene.cargo.register()
explosives.cargo.register()
farm_supplies.cargo.register()
ferrochrome.cargo.register()
fertiliser.cargo.register()
fish.cargo.register()
fish_and_meat.cargo.register()
flour.cargo.register()
food.cargo.register()
forgings_and_castings.cargo.register()
food_additives.cargo.register()
formic_acid.cargo.register()
fruits.cargo.register()
furniture.cargo.register()
glass.cargo.register()
goods.cargo.register()
grain.cargo.register()
hydrochloric_acid.cargo.register()
hydrogen.cargo.register()
hardware.cargo.register()
iron_ore.cargo.register()
kaolin.cargo.register()
lifting_equipment.cargo.register()
livestock.cargo.register()
limestone.cargo.register()
logs.cargo.register()
lumber.cargo.register()
lye.cargo.register()
mail.cargo.register()
maize.cargo.register()
manganese.cargo.register()
meat.cargo.register()
methanol.cargo.register()
milk.cargo.register()
naphtha.cargo.register()
nickel.cargo.register()
nitrates.cargo.register()
nitrogen.cargo.register()
nuts.cargo.register()
oil.cargo.register()
oil_seeds.cargo.register()
oxygen.cargo.register()
packaging.cargo.register()
paints_and_coatings.cargo.register()
paper.cargo.register()
passengers.cargo.register()
peat.cargo.register()
petrol.cargo.register()
phosphate.cargo.register()
phosphoric_acid.cargo.register()
pig_iron.cargo.register()
pipe.cargo.register()
pipework.cargo.register()
plastics.cargo.register()
plastic_parts.cargo.register()
plant_fibres.cargo.register()
potash.cargo.register()
propylene.cargo.register()
concrete_products.cargo.register()
pumps_and_valves.cargo.register()
pyrite_ore.cargo.register()
quicklime.cargo.register()
rare_metals.cargo.register()
raw_latex.cargo.register()
rebar.cargo.register()
recyclables.cargo.register()
rubber.cargo.register()
sand.cargo.register()
salt.cargo.register()
scrap_metal.cargo.register()
slag.cargo.register()
soda_ash.cargo.register()
stainless_steel.cargo.register()
steel.cargo.register()
steel_merchant_bar.cargo.register()
steel_pipe.cargo.register()
steel_sections.cargo.register()
steel_sheet.cargo.register()
steel_tube.cargo.register()
steel_wire_rod.cargo.register()
steel_wire_rope.cargo.register()
stone.cargo.register()
sugar.cargo.register()
sugarcane.cargo.register()
sugar_beet.cargo.register()
sulphur.cargo.register()
sulphuric_acid.cargo.register()
textiles.cargo.register()
timber.cargo.register()
tin.cargo.register()
tinplate.cargo.register()
tyre_cord.cargo.register()
tyres.cargo.register()
urea.cargo.register()
vehicle_bodies.cargo.register()
vehicle_engines.cargo.register()
vehicle_parts.cargo.register()
vehicles.cargo.register()
welding_consumables.cargo.register()
wool.cargo.register()
yarn.cargo.register()
zinc.cargo.register()
